package com.seta.staffreport.persisted;

// Generated Mar 2, 2015 10:31:43 PM by Hibernate Tools 3.4.0.CR1

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

    private Integer testId;
    private String testName;

    public Test() {
    }

    public Test(String testName) {
        this.testName = testName;
    }

    public Integer getTestId() {
        return this.testId;
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    public String getTestName() {
        return this.testName;
    }

    public void setTestName(String testName) {
        this.testName = testName;
    }

}
