package com.seta.staffreport.persisted;

// Generated Jan 23, 2015 10:32:31 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Employees generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Employees implements java.io.Serializable {

	private Integer empId;
	private Division division;
	private Team team;
	private String empFullName;
	private Date joinDate;
	private String empSkills;
	private Date empBirthday;
	private String empPhone;
	private String empContact;
	private String empAvatar;
	private Integer empStatus;
	private Set employeehistories = new HashSet(0);
	private Set admins = new HashSet(0);

	public Employees() {
	}

	public Employees(Integer empId) {
		super();
		this.empId = empId;
	}

	public Employees(String empFullName, Date joinDate) {
		this.empFullName = empFullName;
		this.joinDate = joinDate;
	}

	public Employees(Division division, Team team, String empFullName, Date joinDate, String empSkills,
			Date empBirthday, String empPhone, String empContact, String empAvatar, Integer empStatus,
			Set employeehistories, Set admins) {
		this.division = division;
		this.team = team;
		this.empFullName = empFullName;
		this.joinDate = joinDate;
		this.empSkills = empSkills;
		this.empBirthday = empBirthday;
		this.empPhone = empPhone;
		this.empContact = empContact;
		this.empAvatar = empAvatar;
		this.empStatus = empStatus;
		this.employeehistories = employeehistories;
		this.admins = admins;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	public String getEmpFullName() {
		return this.empFullName;
	}

	public void setEmpFullName(String empFullName) {
		this.empFullName = empFullName;
	}

	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public String getEmpSkills() {
		return this.empSkills;
	}

	public void setEmpSkills(String empSkills) {
		this.empSkills = empSkills;
	}

	public Date getEmpBirthday() {
		return this.empBirthday;
	}

	public void setEmpBirthday(Date empBirthday) {
		this.empBirthday = empBirthday;
	}

	public String getEmpPhone() {
		return this.empPhone;
	}

	public void setEmpPhone(String empPhone) {
		this.empPhone = empPhone;
	}

	public String getEmpContact() {
		return this.empContact;
	}

	public void setEmpContact(String empContact) {
		this.empContact = empContact;
	}

	public String getEmpAvatar() {
		return this.empAvatar;
	}

	public void setEmpAvatar(String empAvatar) {
		this.empAvatar = empAvatar;
	}

	public Integer getEmpStatus() {
		return this.empStatus;
	}

	public void setEmpStatus(Integer empStatus) {
		this.empStatus = empStatus;
	}

	public Set getEmployeehistories() {
		return this.employeehistories;
	}

	public void setEmployeehistories(Set employeehistories) {
		this.employeehistories = employeehistories;
	}

	public Set getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set admins) {
		this.admins = admins;
	}

}
