package com.seta.staffreport.persisted;

// Generated Jan 28, 2015 1:37:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * File generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class File implements java.io.Serializable {

	private Integer id;
	private String fileName;
	private byte[] content;
	private String type;
	private Set images = new HashSet(0);

	public File() {
	}

	public File(Integer id) {
		this.id = id;
	}

	public File(String fileName) {
		this.fileName = fileName;
	}

	public File(String fileName, byte[] content, String type, Set images) {
		this.fileName = fileName;
		this.content = content;
		this.type = type;
		this.images = images;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getImages() {
		return this.images;
	}

	public void setImages(Set images) {
		this.images = images;
	}

}
