package com.seta.staffreport.persisted;

// Generated Jan 28, 2015 1:37:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Image generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Image implements java.io.Serializable {

	private Integer id;
	private File file;
	private String name;
	private Set employeeses = new HashSet(0);

	public Image() {
	}

	public Image(Integer id) {
		this.id = id;
	}

	public Image(File file, String name) {
		this.file = file;
		this.name = name;
	}

	public Image(File file, String name, Set employeeses) {
		this.file = file;
		this.name = name;
		this.employeeses = employeeses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set employeeses) {
		this.employeeses = employeeses;
	}

}
