package com.seta.staffreport.persisted;

// Generated Jan 27, 2015 2:55:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private Integer id;
	private File file;
	private String name;

	public Image() {
	}

	public Image(File file, String name) {
		this.file = file;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
